### PR TITLE
Removing providers and moving into definitions

### PR DESCRIPTION
**Pull request by sbotman**
Using definitions removes a lot of the complexity. Also the output during the chef-converge will be more clean, because this information didn't added any value since the state was always "up-to-date".

### CODE REVIEW

**Comment by sbotman** [comment]
@snkutlu Suleyman, please review this one for me. All test-kitchen tests are green, so you can test within you environments.

**Comment by snkutlu** [comment]
@sbotman, testing in real life today...

**Comment by sbotman** [comment]
@snkutlu thank you sir!

**Comment by sbotman** [comment]
Will close this PR and reopen a new one to trigger the travis build to check the code.

**Pull request closed without merging**
