### PR TITLE
Update documentation for large installation tweaks and remove old attribute

### PR DESCRIPTION
**Pull request by wilb**
Fixes https://github.com/sous-chefs/nagios/issues/503

### CODE REVIEW

**Comment by damacus** [comment]
Hey @wilb! 
thanks for the contribution. 

could you fix those failure please? Give us a shout if you need a hand with it

**Comment by wilb** [comment]
Hmmm, based on the scope of my change I'm not sure that it's caused the failures... Will take a look.

**Comment by wilb** [comment]
Yeah, after updating my PR with master those fails are not related to this. Most now pass, but the fails are limited to:

```"Property `sensitive` of resource `yum_repository` overwrites an existing method. Please use a different property name. This will raise an exception in Chef 13. (CHEF-11)/opt/kitchen/cache/cookbooks/yum/resources/repository.rb:59:in `class_from_file'.\nPlease see https://docs.chef.io/deprecations_property_name_collision.html for further details and information on how to correct this problem. at /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/formatters/doc.rb:419:in `deprecation'"```

and 

```[2017-07-26T21:00:29+00:00] ERROR: "Property `sensitive` of resource `yum_repository` overwrites an existing method. Please use a different property name. This will raise an exception in Chef 13. (CHEF-11)/opt/kitchen/cache/cookbooks/yum/resources/repository.rb:59:in `class_from_file'.\nPlease see https://docs.chef.io/deprecations_property_name_collision.html for further details and information on how to correct this problem. at /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/formatters/doc.rb:419:in `deprecation'"```

**Comment by shoekstra** [comment]
@wilb don't worry to investigate further, the issues are with other cookbooks which we are already addressing.

The yum related errors will disappear once 4-20ma/cookbook-fcgiwrap_rpm#68 has been merged and released and nginx-centos-7 should be resolved once someara/dokken-images#9 has been merged

**Review by tas50 — APPROVED** [review]

**Pull request merged**
