### PR TITLE
Enable custom options

### PR DESCRIPTION
**Pull request by sbotman**
This will allow custom options on hosts, contacts and services.

### CODE REVIEW

**Comment by sbotman** [comment]
rebase was needed, waiting for test to become green

**Comment by sbotman** [comment]
Needs a refactor before merging!

**Comment by sbotman** [comment]
related to #399

**Comment by sbotman** [comment]
@jhammerman79, could you please test this for me and share your findings.

**Comment by snkutlu** [comment]
Merging...

**Pull request merged**
