### PR TITLE
Make source URL configurable

### PR DESCRIPTION
**Pull request by bikramj**
# Description
We are restricting outgoing internet access to our machines and the community cookbook is not able to go to assets.nagios.com to grab source code. Want the source URL configurable so that we can download it from our local Nexus proxy repo

## Issues Resolved

List any existing issues this PR resolves

## Check List

- [ ] A summary of changes made is included in the CHANGELOG under `## Unreleased`
- [ ] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by bikramj** [comment]
Unable to add/edit Label. It should have `Release: Patch` label

**Comment by bikramj** [comment]
Can someone please help with this?

**Comment by ramereth** [comment]
@bikramj can you please update and rebase?

**Review by damacus — APPROVED** [review]

**Comment by kitchen-porter** [comment]
Released as: [11.3.0](https://github.com/sous-chefs/nagios/releases/tag/11.3.0)

**Pull request merged**
