### PR TITLE
Make server configuration optional

### PR DESCRIPTION
**Pull request by codayblue**
## Description

Allow nagios configuration to be configured so that it is not blow away if deployed by other means. Example: Github -> jenkins -> nagios server

### Issues Resolved

[List any existing issues this PR resolves]

### Check List
- [ ] All tests pass. See https://github.com/sous-chefs/apache2/blob/master/TESTING.md
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by codayblue** [comment]
Might have a better idea. Please hold on this one.

**Comment by codayblue** [comment]
Updated with a better way to handle configuration file management.

**Comment by xorima** [comment]
@codayblue 

if you go into `.github/workflows` you will find a section listing the `suites` could you add your new suite there?

I am working on fixing the tests in #600 but if it takes too long I can just merge this in :+1:

**Comment by codayblue** [comment]
@Xorima I have added the suite to the workflow. I also forgot to add the test back when I rebased so that is in there now as well.

**Review by xorima — APPROVED** [review]

**Comment by xorima** [comment]
Released as 8.2.0, thanks!

**Pull request merged**
