### PR TITLE
add forbid_zero arg to allow zero for notification_interval (but not retry_interval or check_interval)

### PR DESCRIPTION
**Pull request by ghost**
fix for issue #476

added a boolean option to nagios_interval as to wether it should forbid a value of zero for a particular interval type

### CODE REVIEW

**Comment by sbotman** [comment]
Sorry for the delay in reviewing this PR. I think it's better to move this logic towards the model. I will try to give an example...

**Comment by sbotman** [comment]
Just some thoughts.. think we should remove the fail check from the nagios_interval function.

```
- if seconds.to_i == 0
-   fail ArgumentError, 'Specified nagios interval of 0 seconds is not allowed'
- end
```

And within the model in the method check_interval we should add the logic.
So for example we should update:
https://github.com/schubergphilis/nagios/blob/master/libraries/host.rb#L229-L231
With something like:

```
def check_interval=(int)
  @check_interval = check_integer(int)
  if @check_interval == 0
    fail ArgumentError, 'Specified check_integer interval of 0 seconds is not allowed'
  end
  @check_interval
end
```

And of course we should update all the other methods that cannot be 0.

**Comment by TheCase** [comment]
Sounds good - I'll rework the PR.

**Comment by sbotman** [comment]
Let me correct myself:

```
def check_interval=(int)
  if check_integer(int) == 0
    fail ArgumentError, 'Specified check_integer interval of 0 seconds is not allowed'
  end
  @check_interval = check_integer(int)
end
```

Think this should even be sufficient.

**Comment by sbotman** [comment]
Please rebase the branch when you make the adjustments.

**Comment by sbotman** [comment]
@TheCase any updates on this?

**Comment by TheCase** [comment]
sorry - haven't made time.  I'll put it on my todo list.

**Comment by matl33t** [comment]
Was there a resolution for this issue? Bumping from 7.2.2 to 7.2.6 no longer allows zero for the notification interval which is resulting in a lot more email noise.

**Pull request closed without merging**
