### PR TITLE
Missing stylesheet on Ubuntu 14.04.

### PR DESCRIPTION
**Pull request by leoditommaso**
When using Nagios, main page look for stylesheets on /stylesheets but
hosts and services frames look for styles on /nagios3/stylesheets.

### CODE REVIEW

**Comment by sbotman** [comment]
I would love to merge this, but I don't like the hardcoded path '/nagios3/stylesheets' in here.
Next to that, I don't have enough ubuntu experience, so maybe it's better if I leave this one for @tas50

**Comment by leoditommaso** [comment]
The template as it is it's currently not working in Ubuntu 14.04 and with this fix it works, sure could be done better. Anyway, in the cookbook template /stylesheets path is currently hardcoded. For now, I'm just overwriting this cookbook template with a custom template to get it work.

**Comment by leoditommaso** [comment]
@sbotman any news on this?

**Comment by tas50** [comment]
Merging this, but we still need to resolve https://github.com/tas50/nagios/issues/327 to get 14.04 working out of the box

**Pull request merged**
