### PR TITLE
documentation correction. It's actually node['nagios']['server']['server_alias']

### PR DESCRIPTION
**Pull request by amandasaurus**
Make the documentaiton match the code.

### CODE REVIEW

**Comment by sbotman** [comment]
Just some thoughts...
While this is broken anyway, why not change the templates/default/apache2.conf.erb  and make the attribute node['nagios']['server']['alias']

**Comment by amandasaurus** [comment]
@sbotman Yeah either the docs or code should change. But I wanted to make it more backwards compatible, and changed the docs. My ruby/chef-foo isn't good enough to confidently start mucking around with templates

**Comment by sbotman** [comment]
@rory Looking at the attributes they are scattered all over the place. 
Really would like to clean this up and make every attribute configureable.
This might mean moving some attributes to other places because they conflict.
Hopefully we will have some other people react on this so we can start a conversation and hear some other thoughts.

My Idea will be moving/renaming attributes into the right place, eg:
`default['nagios']['key']` All nagios host configuration settings.
`default['nagios']['cgif']['key']` All cgi configuration settings.
`default['nagios']['conf']['key']` All server configuration settings.
`default['nagios']['server']['key']` All server settings.
`default['nagios']['default_host']['key']` All default_host template settings.

This will mean moving most attributes currently under `default['nagios']` into `default['nagios']['server']`
Impact well be huge, but this will make stuff more clear.

**Comment by amandasaurus** [comment]
Perhaps. I have no strong opinion on a refactor like that. I'm new to Chef. I was just suggesting fixing _this_ documentation error.

**Comment by sbotman** [comment]
Oke, well lets see what @tas50 opinion will be and merge this or rename.

**Pull request merged**
