### PR TITLE
fixing escalation_periods

### PR DESCRIPTION
**Pull request by Maigard**
Escalation_periods aren't aren't getting copied out of the escalation data bags.

### CODE REVIEW

**Comment by sbotman** [comment]
Just quickly looked at this and it seems that the host/service escalation databags are loaded before the timeperiods within the _load_databag_config.rb recipe. Could you test if your problem is solved by moving them after the timeperiods? Cheers Sander

**Comment by Maigard** [comment]
I moved the host and service escalations just below the timeperiod section in the _load_databag_config.rb, and it still removes the escalation_period from the escalation definition.

**Comment by sbotman** [comment]
Oke, so I guess we need to update the import function for this...

**Comment by sbotman** [comment]
So I have checked the other timeperiods and seems that I'm not checking on the relations. So your pull request would indeed be the best solution.

**Pull request merged**
