### PR TITLE
Removing providers

### PR DESCRIPTION
**Pull request by sbotman**
Removing providers and moving into definitions

### CODE REVIEW

**Comment by sbotman** [comment]
@snkutlu recreated the PR because travis missed the old one. Lets see if this one gets triggered.

**Comment by sbotman** [comment]
Well, travis has started but seems that it cannot reach the supermarket on app-supermarket-prod-i-c663c400.opscode.us :(
Think that @snkutlu will need to do all the testing...

**Comment by snkutlu** [comment]
@sbotman. I experienced the same and did some steps manually. Now kitchen can find all necessary cookbooks, testing continues.. 

Will report hopefully soon..

**Comment by snkutlu** [comment]
All tests passed. Can be merged..

**Pull request merged**
