### PR TITLE
Fixes #421 by allowing pagerduty contact to be added to the admins contactgroup

### LINKED ISSUE #421: The PagerDuty integration is broken
The nagios::pagerduty recipe does not add the pagerduty contacts to the "admins" contact group.

### PR DESCRIPTION
**Pull request by ovaistariq**

### CODE REVIEW

**Comment by sbotman** [comment]
This has some simple rubocop errors that can be fixed, but I wonder if this will work....
The `contactgroups = ["admins"] if pagerduty_contact['admin_contactgroup']` is pointing to the pagerduty_contact and I cannot seem to find this anywhere. Will do a kitchen test to see if this works.

**Comment by sbotman** [comment]
So this indeed fails if I setup the test-kitchen environment with your branch, error is:

```
     ================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/nagios/recipes/pagerduty.rb
       ================================================================================

       NameError
       ---------
       No resource, method, or local variable named `pagerduty_contact' for `Chef::Recipe "pagerduty"'
```

Guess we missing some info here... 
Btw, really appreciate your help and explanation in the ticket. Think your idea is great, we just need to make it work in the right way :)

Greetings Sander

**Comment by ovaistariq** [comment]
My bad here. I didn't properly test it. My wrapper cookbook had some additional logic and I forgot to correct the variable name in this PR. I will fix it.

**Comment by sbotman** [comment]
Just for information, I have tested the `'contactgroups'   => contact['contactgroups']` without setting it within the databag and didn't get any nil error. So could not reproduce your problem :(

**Comment by ovaistariq** [comment]
@sbotman I have made the changes as we discussed and the tested them against rhel and debian platform_family. I have added test pagerduty contacts, one of which sets contactgroups and the other one doesn't and the tests pass.

**Comment by sbotman** [comment]
For information we have received the following response of Pagerduty support:

```
Jonathan Curry (PagerDuty Support)
Oct 5, 08:27

Hi Sander,

Thanks for reaching out. The PagerDuty contact in Nagios should be added to the main contact group so
that it will receive Nagios alerts, and for most users the main contact group is the admins group, 
so you probably do want to go ahead and merge Ovais Tariq's PR.

I hope this helps!

Cheers,

Jonathan
```

But the solution that we have implemented makes the contactgroups variable depending on user input, so very flexible.

**Comment by ovaistariq** [comment]
@sbotman indeed the current solution is very flexible.

**Pull request merged**
